export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 2499,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    description: "Premium wireless headphones with noise cancellation and 30-hour battery life.",
    sellerName: "TechStore",
    stock: 15,
  },
  {
    id: 2,
    name: "Running Shoes",
    price: 3299,
    category: "Footwear",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    description: "Lightweight running shoes with breathable mesh and cushioned sole.",
    sellerName: "SportsHub",
    stock: 8,
  },
  {
    id: 3,
    name: "Coffee Maker",
    price: 4599,
    category: "Home Appliances",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
    description: "Automatic coffee maker with programmable timer and 12-cup capacity.",
    sellerName: "HomeEssentials",
    stock: 0,
  },
  {
    id: 4,
    name: "Yoga Mat",
    price: 899,
    category: "Fitness",
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400",
    description: "Non-slip yoga mat with extra cushioning, perfect for home workouts.",
    sellerName: "FitLife",
    stock: 25,
  },
  {
    id: 5,
    name: "Smart Watch",
    price: 5999,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
    description: "Fitness tracking smart watch with heart rate monitor and GPS.",
    sellerName: "TechStore",
    stock: 12,
  },
  {
    id: 6,
    name: "Backpack",
    price: 1799,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
    description: "Durable laptop backpack with multiple compartments and water resistance.",
    sellerName: "TravelGear",
    stock: 20,
  },
]

export const categories = [...new Set(products.map(p => p.category))]